services:

  db:
    image: postgres:15
    container_name: postgres_auth
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: unless-stopped

  auth:
    build: .
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped